#!/usr/bin/env bash

function createProject()
{
    echo "🔧 Creating database..."
    mysql -h 'localhost' -u root ${ROOT_PASSWORD} -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME};"

    echo "🔧 Creating Laravel project named $NAME..."
    laravel new $NAME --branch=main --jet --stack=livewire --quiet > /dev/null 2>&1

    echo "🔧 Navigating to project directory..."
    cd $NAME

    echo "🔧 Initial Commit..."
    git init > /dev/null 2>&1 && git add . > /dev/null 2>&1 && git commit -m "Initial Commit"  --quiet

    echo "🔧 Updating MAIL configuration..."
    cp .env .env.example
    sed 's/MAIL_FROM_ADDRESS=null/MAIL_FROM_ADDRESS=noreply@app.com/g' .env.example > .env

    echo "🔧 Updating .env.example configuration..."
    cp .env .env.example
    git add . > /dev/null 2>&1 && git commit -m "Update .env.example"  --quiet

    echo "🔧 Updating README.md..."
    sed "s/YOUR_APP/${NAME}/g" $SNAP_PATH/stubs/README.md > README.md
    git add . > /dev/null 2>&1 && git commit -m "Update README.md"  --quiet

    echo "🔧 Installing packages..."
    composer require \
    rappasoft/laravel-livewire-tables \
    blade-ui-kit/blade-icons \
    rap2hpoutre/laravel-log-viewer \
    diglactic/laravel-breadcrumbs \
    predis/predis \
    cleaniquecoders/laravel-observers \
    cleaniquecoders/laravel-uuid \
    lab404/laravel-impersonate \
    livewire/livewire \
    owen-it/laravel-auditing \
    spatie/laravel-activitylog \
    spatie/laravel-medialibrary \
    spatie/laravel-tags \
    spatie/laravel-permission \
    yadahan/laravel-authentication-log \
    --quiet --no-ansi --no-interaction
    git add . > /dev/null 2>&1 && git commit -m "Added common packages"  --quiet

    echo "🔧 Installing development packages..."
    composer require \
    barryvdh/laravel-debugbar  \
    nunomaduro/larastan \
    spatie/laravel-ray \
    friendsofphp/php-cs-fixer \
    --quiet --no-ansi --no-interaction --dev
    git add . > /dev/null 2>&1 && git commit -m "Added development packages"  --quiet

    echo "🔧 Publishing packages config and assets..."
    php artisan vendor:publish --all --force --quiet
    git add . > /dev/null 2>&1 && git commit -m "Publishing packages config and assets"  --quiet

    echo "🔧 Setting up front-end assets..."
    yarn install --silent > /dev/null 2>&1
    cp $SNAP_PATH/stubs/webpack.mix.js .
    npm run prod > /dev/null 2>&1
    git add . > /dev/null 2>&1 && git commit -m "Setting up front-end assets"  --quiet

    echo "🔧 Copying stubs..."
    # Need to copy the stubs from snap/stubs absolute directory to  project directory
    cp -R $SNAP_PATH/stubs/.github .
    cp -R $SNAP_PATH/stubs/app .
    cp -R $SNAP_PATH/stubs/bin .
    cp -R $SNAP_PATH/stubs/config .
    cp -R $SNAP_PATH/stubs/database .
    cp -R $SNAP_PATH/stubs/resources .
    cp -R $SNAP_PATH/stubs/routes .
    cp -R $SNAP_PATH/stubs/storage .
    cp -R $SNAP_PATH/stubs/support .
    cp -R $SNAP_PATH/stubs/tinker .
    cp $SNAP_PATH/stubs/.php-cs-fixer.php .
    cp $SNAP_PATH/stubs/phpstan.dist .
    git add . > /dev/null 2>&1 && git commit -m "Copied stubs"  --quiet

    echo "🔧 Creating develop branch..."
    git checkout -b develop 

    echo "🔧 Run the migrations..."
    php artisan reload:db > /dev/null 2>&1

    echo "🚀 Installation completed!"
    echo ""

    echo "Launching the project in Visual Studio Code"
    code .
    
    clear

    echo "Serve the project"
    php artisan serve
}

NAME="project"

if [ $1 ];
then
    NAME=$1
fi

if [ -d $NAME ];
then 
    NAME="$NAME"_"$(openssl rand -hex 2)"
    echo "⚠️  Project renamed to $NAME because project name provided already exists"
fi

BIN_MYSQL=$(which mysql)
ROOT_PASSWORD=

DB_HOST='localhost'
DB_NAME=$NAME

createProject
